spring.application.name=demo
# H2インメモリDB（起動時に自動作成→再起動でリセット）
spring.datasource.url=jdbc:h2:mem:testdb
# H2 JDBCドライバ指定
spring.datasource.driverClassName=org.h2.Driver
# エンティティに合わせてスキーマを自動更新（開発・演習向け）
spring.jpa.hibernate.ddl-auto=update
# H2コンソール有効化（http://localhost:8080/h2-console）
spring.h2.console.enabled=true